[package]
name = "rich-presence-mpris"
version = "0.1.0"
edition = "2021"
authors = ["lilithium-hydride"]
description = "MPRIS integration with Discord Rich Presence"

[dependencies]
discord-rich-presence = "0.2.0"
mpris = "2.0.0-rc2"
urlencoding = "2.1.0"
tap = "1.0.1"